"""AI orchestration router.

User request -> AI Router -> Model selection -> Provider -> Structured response
-> Schema validation -> Safety/business-rule validation -> Frontend.

Also hosts the weather-aware itinerary endpoint. When a real AI provider is
configured the itinerary is generated by the model; otherwise a deterministic,
rule-based itinerary keeps the feature fully functional (clearly labelled with
is_ai_generated=False and data_source="rules_engine").
"""

from typing import Any

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from ..ai.providers import get_provider
from ..services.weather import (
    WeatherServiceError,
    _day_weather_payload,
    build_alerts,
    generate_deterministic_itinerary,
    get_forecast_cached,
)

router = APIRouter(prefix="/ai", tags=["ai"])


class RecommendRequest(BaseModel):
    origin: str
    destination: str
    options: list[dict[str, Any]] = Field(..., description="Normalized transport options")
    profile: str | None = None
    preference: str | None = Field(None, description="Force provider: mock|openrouter|direct")


class RecommendResponse(BaseModel):
    recommendation: str
    explanation: str
    best_option_id: str | None = None
    confidence: float
    is_ai_generated: bool = True
    data_source: str = "ai_generated"


RECOMMEND_SCHEMA = {
    "type": "object",
    "properties": {
        "recommendation": {"type": "string"},
        "explanation": {"type": "string"},
        "best_option_id": {"type": "string"},
        "confidence": {"type": "number"},
        "is_ai_generated": {"type": "boolean"},
    },
    "required": ["recommendation", "explanation", "confidence"],
}


@router.post("/recommend", response_model=RecommendResponse)
async def ai_recommend(request: RecommendRequest):
    """Generate a personalized travel recommendation using structured options."""
    if not request.options:
        raise HTTPException(status_code=400, detail="No options provided")

    provider = get_provider(request.preference)

    # Build a factual context from structured (non-AI) data
    ctx_lines = []
    for o in request.options:
        ctx_lines.append(
            f"- {o.get('mode')} ({o.get('service_name')}): ₹{o.get('price')}, "
            f"{o.get('duration')} min, comfort {o.get('comfort')}, convenience {o.get('convenience')}, "
            f"demo={o.get('is_demo')}"
        )
    ctx = "\n".join(ctx_lines)

    prompt = (
        f"User travels {request.origin} -> {request.destination}. "
        f"Preference profile: {request.profile or 'balanced'}. "
        "Recommend one option and explain why. Reference only the options below. "
        "Do not invent prices or availability.\n"
        f"{ctx}"
    )

    try:
        structured = await provider.extract(prompt, RECOMMEND_SCHEMA)
    except (NotImplementedError, RuntimeError, ValueError):
        # Fallback for providers without extract or without keys
        text = await provider.chat([{"role": "user", "content": prompt}])
        structured = {
            "recommendation": text,
            "explanation": text,
            "best_option_id": None,
            "confidence": 0.5,
            "is_ai_generated": True,
        }
    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail=f"AI provider unavailable: {type(e).__name__}",
        ) from e

    # Safety validation: ensure recommendation references real option ids
    valid_ids = {o.get("id") for o in request.options}
    best = structured.get("best_option_id")
    if best and best not in valid_ids:
        structured["best_option_id"] = None

    return RecommendResponse(**structured)


class ItineraryRequest(BaseModel):
    destination: str = Field(..., min_length=1)
    origin: str | None = None
    start_date: str
    end_date: str
    travelers: int = Field(default=2, ge=1, le=20)
    budget: str | None = Field(None, description="budget | midrange | luxury")
    trip_type: str | None = Field(None, description="leisure | adventure | culture | family | ...")
    preferences: str | list[str] | None = None
    lat: float | None = None
    lon: float | None = None
    preference: str | None = Field(None, description="Force provider: mock|openrouter|direct")


class ItineraryResponse(BaseModel):
    destination: str
    start_date: str
    end_date: str
    trip_type: str
    weather_available: bool
    weather_note: str | None = None
    forecast: list[dict[str, Any]] | None = None
    itinerary: list[dict[str, Any]]
    summary: str
    alerts: list[dict[str, Any]]
    is_ai_generated: bool
    data_source: str


ITINERARY_SCHEMA = {
    "type": "object",
    "properties": {
        "itinerary": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "date": {"type": "string"},
                    "activities": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "title": {"type": "string"},
                                "type": {"type": "string"},
                                "time": {"type": "string"},
                            },
                            "required": ["title"],
                        },
                    },
                },
                "required": ["date", "activities"],
            },
        },
        "summary": {"type": "string"},
    },
    "required": ["itinerary", "summary"],
}


def _validate_dates(start_date: str, end_date: str) -> tuple[str, str]:
    from datetime import datetime

    try:
        start = datetime.fromisoformat(start_date).date()
        end = datetime.fromisoformat(end_date).date()
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid date format. Use YYYY-MM-DD.")
    if end < start:
        raise HTTPException(status_code=400, detail="end_date must be on or after start_date.")
    return start.isoformat(), end.isoformat()


def _weather_context(forecast: list[Any]) -> str:
    lines = []
    for day in forecast:
        category = _day_weather_payload(day)
        lines.append(
            f"- {day.date}: {day.description}, {day.temperature:.0f}°C, "
            f"{day.precipitation_probability}% rain, wind {day.wind_speed:.0f} km/h "
            f"-> {category['category']}"
        )
    return "\n".join(lines)


def _merge_weather(
    itinerary: list[dict[str, Any]],
    forecast_by_date: dict[str, Any],
) -> list[dict[str, Any]]:
    for day in itinerary:
        weather = forecast_by_date.get(day.get("date", ""))
        if weather is not None:
            payload = _day_weather_payload(weather)
            day.setdefault("weather", payload)
            day.setdefault("category", payload["category"])
            day.setdefault("category_label", payload["category_label"])
            day.setdefault("category_icon", payload["category_icon"])
            day.setdefault("day_label", "Day")
        for activity in day.get("activities", []):
            activity.setdefault("type", "general")
    return itinerary


@router.post("/itinerary", response_model=ItineraryResponse)
async def ai_itinerary(request: ItineraryRequest):
    """Generate a weather-aware trip itinerary for a destination and date range."""
    start, end = _validate_dates(request.start_date, request.end_date)

    # Weather is a nice-to-have; trip planning must never break because of it.
    try:
        forecast = await get_forecast_cached(
            request.destination,
            lat=request.lat,
            lon=request.lon,
            start_date=start,
            end_date=end,
        )
        weather_available = True
    except WeatherServiceError:
        forecast = []
        weather_available = False

    provider = get_provider(request.preference)
    is_real_ai = provider.name != "MockAIProvider"

    if weather_available and is_real_ai:
        try:
            prompt = (
                f"Plan a {request.travelers}-traveler {request.trip_type or 'leisure'} trip to "
                f"{request.destination} from {start} to {end}. "
                f"Budget: {request.budget or 'balanced'}. Preferences: {request.preferences or 'none'}. "
                "Weather-aware daily forecast:\n"
                f"{_weather_context(forecast)}\n"
                "Return a day-by-day itinerary (one entry per date) with activities that match "
                "the weather. Prefer outdoor activities on good days and indoor activities on "
                "wet or extreme days. Include a one-paragraph summary. "
                "Do not invent bookings, prices or hotel names."
            )
            structured = await provider.extract(prompt, ITINERARY_SCHEMA)
            forecast_by_date = {d.date: d for d in forecast}
            result = {
                "destination": request.destination,
                "start_date": start,
                "end_date": end,
                "trip_type": request.trip_type or "leisure",
                "weather_available": True,
                "weather_note": None,
                "forecast": [_day_weather_payload(d) for d in forecast],
                "itinerary": _merge_weather(structured.get("itinerary", []), forecast_by_date),
                "summary": structured.get("summary", ""),
                "alerts": build_alerts(forecast),
                "is_ai_generated": True,
                "data_source": "ai_generated",
            }
        except Exception:  # noqa: BLE001 - any AI failure falls back to the rules engine
            # Any AI failure falls back to the deterministic, safe generator.
            result = generate_deterministic_itinerary(
                request.destination,
                start,
                end,
                forecast,
                trip_type=request.trip_type,
                preferences=request.preferences,
            )
            result["weather_available"] = True
            result["weather_note"] = None
            result["forecast"] = [_day_weather_payload(d) for d in forecast]
    elif weather_available:
        result = generate_deterministic_itinerary(
            request.destination,
            start,
            end,
            forecast,
            trip_type=request.trip_type,
            preferences=request.preferences,
        )
        result["weather_available"] = True
        result["weather_note"] = None
        result["forecast"] = [_day_weather_payload(d) for d in forecast]
    else:
        # No weather at all: still produce a sensible static plan.
        from datetime import datetime, timedelta

        def _dates(start: str, end: str) -> list[str]:
            cur = datetime.fromisoformat(start).date()
            last = datetime.fromisoformat(end).date()
            out = []
            while cur <= last:
                out.append(cur.isoformat())
                cur += timedelta(days=1)
            return out

        days = _dates(start, end)
        itinerary = [
            {
                "date": d,
                "day_label": f"Day {i + 1}",
                "activities": [
                    {"icon": "🚕", "title": "Arrival & hotel check-in", "type": "logistics", "time": "Morning"},
                    {"icon": "🏛️", "title": "Explore the highlights", "type": "outdoor", "time": "Afternoon"},
                    {"icon": "🍽️", "title": "Dinner at a local favourite", "type": "food", "time": "Night"},
                ],
                "weather": None,
            }
            for i, d in enumerate(days)
        ]
        result = {
            "destination": request.destination,
            "start_date": start,
            "end_date": end,
            "trip_type": request.trip_type or "leisure",
            "weather_available": False,
            "weather_note": "Weather information is temporarily unavailable.",
            "forecast": None,
            "itinerary": itinerary,
            "summary": f"A {len(days)}-day plan for {request.destination}. Weather data is unavailable, so "
            "this is a general itinerary you can refine.",
            "alerts": [],
            "is_ai_generated": False,
            "data_source": "rules_engine",
        }

    return ItineraryResponse(**result)